Fix indentation for fail job step in test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -85,11 +85,11 @@ jobs:
           target/surefire-reports/
         if-no-files-found: error
 
-      - name: Fail job if tests failed
-        if: always() && steps.run-tests.outcome == 'failure'
-        run: |
-          echo "::error::One or more Maven tests failed."
-          exit 1
+    - name: Fail job if tests failed
+      if: always() && steps.run-tests.outcome == 'failure'
+      run: |
+        echo "::error::One or more Maven tests failed."
+        exit 1
 
   frontend:
     name: Build and Test Frontend
